sudo: false
language: python
services:
  - memcached
  - mysql
  - riak
  - postgresql
  - redis-server
  - cassandra
python:
  - "3.4"
branches:
  only:
  - master
env:
  matrix:
    - TEST_SUITE=sqlite DB=sqlite
    - TEST_SUITE=postgres DB=postgres
    - TEST_SUITE=mysql DB=mysql
    - TEST_SUITE=acceptance
    - TEST_SUITE=js
    - TEST_SUITE=cli
    - TEST_SUITE=dist
  global:
    - PIP_DISABLE_PIP_VERSION_CHECK=on
    - SENTRY_LIGHT_BUILD=1
    - SENTRY_SKIP_BACKEND_VALIDATION=1
    - SELENIUM_DRIVER=firefox
install:
  - pip install -r requirements.txt
