sudo: false
language: python
services:
  - memcached
  - mysql
  - riak
  - postgresql
  - redis-server
  - cassandra
python:
  - "3.4"
branches:
  only:
  - master
install:
  - pip install -r requirements.txt
